sudo: false

language: python

python:
  - "3.6"

before_install:
  - pip install --upgrade pip

install:
  - pip install numpy
  - pip install matplotlib


before_script:
  - uname -a
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - printenv |sort
  

script:
  - ls -al
  - make check
  - python3 movingTraps.py
  - python3 functions
  - make clean 
  